[package]
name = "web-practice-6-static"
version = "0.1.0"

[fs]
"/public" = "public"

[[command]]
name = "serve"
module = "wasmer/static-web-server:static-web-server"
runner = "wasi"
[command.annotations.wasi]
main-args = ["--root", "/public", "--addr", "0.0.0.0:8080"]